// <auto-generated />
using System;
using Avanade.Estagiario.API.Repositorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avanade.Estagiario.API.Migrations
{
    [DbContext(typeof(CervejaContext))]
    partial class CervejaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Avanade.Estagiario.API.Domain.Cerveja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Compra")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Gelada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("TeorAlcoolico")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Cervejas");
                });
#pragma warning restore 612, 618
        }
    }
}
